Applying slightly modified patch from Harald Dunkel <harald.dunkel@aixigo.de> to add support for lxc-path in local debian additions (Closes: #706379).

diff --git a/debian/local/lxc-backup b/debian/local/lxc-backup
--- a/debian/local/lxc-backup
+++ b/debian/local/lxc-backup
@@ -12,14 +12,52 @@ set -e
 . /usr/share/lxc/lxc.functions
 
 _LXC_DIRECTORY="${lxc_path}"
-_CONTAINER="${1}"
 
-if [ -n "${_CONTAINER}" ]
+_OPTIONS="$(getopt -o n:,P: -l name:,lxcpath: -- "${@}")"
+
+if [ "${?}" -ne 0 ]
 then
-	shift
-else
-#	echo "Usage: ${0} CONTAINER [BACKUP_NUMBER]"
-	echo "Usage: ${0} CONTAINER"
+	echo "Usage: $(basename ${0}) -n|--name CONTAINER [-P|--lxcpath DIRECTORY]" >&2
+	echo "Usage: $(basename ${0}) -n|--name CONTAINER [-P|--lxcpath DIRECTORY] [BACKUP_NUMBER]" >&2
+	exit 1
+fi
+
+eval set -- "${_OPTIONS}"
+
+while true
+do
+	case "${1}" in
+		-n|--name)
+			_CONTAINER="${2}"
+			shift 2
+			;;
+
+	        -P|--lxcpath)
+			_LXC_DIRECTORY="${2}"
+			shift 2
+			;;
+
+		--)
+			shift
+			break
+			;;
+
+		*)
+			echo "E: $(basename ${0}): internal error ${0}" >&2
+			exit 1
+			;;
+	esac
+done
+
+if [ -z "${_CONTAINER}" ]
+then
+	echo "E: $(basename ${0}): missing container name, use --name option" >&2
+	exit 1
+fi
+
+if [ ! -d "${_LXC_DIRECTORY}" ]
+then
+	echo "E: ${_LXC_DIRECTORY}: no such directory." >&2
 	exit 1
 fi
 
@@ -35,13 +73,13 @@ then
 	exit 1
 fi
 
-if ! lxc-info -n ${_CONTAINER} 2>&1 | grep -qs "STOPPED"
+if ! lxc-info -n ${_CONTAINER} -P "${_LXC_DIRECTORY}" 2>&1 | grep -qs "STOPPED"
 then
 	echo "E: ${_CONTAINER} - not stopped" >&2
 	exit 1
 fi
 
-if [ -e "${_LXC_DIRECTORY}/${_CONTAINER}/rootfs" ]
+if [ -d "${_LXC_DIRECTORY}/${_CONTAINER}/rootfs" ]
 then
 #	if [ -n "${2}" ]
 #	then
diff --git a/debian/local/lxc-list b/debian/local/lxc-list
--- a/debian/local/lxc-list
+++ b/debian/local/lxc-list
@@ -9,6 +9,40 @@
 
 set -e
 
+. /usr/share/lxc/lxc.functions
+
+_LXC_DIRECTORY="${lxc_path}"
+
+_OPTIONS="$(getopt -o P: -l lxcpath: -- "${@}")"
+
+if [ "${?}" -ne 0 ]
+then
+	echo "Usage: $(basename ${0}) [-P|--lxcpath DIRECTORY]" >&2
+	exit 1
+fi
+
+eval set -- "${_OPTIONS}"
+
+while true
+do
+	case "${1}" in
+	        -P|--lxcpath)
+			_LXC_DIRECTORY="${2}"
+			shift 2
+			;;
+
+		--)
+			shift
+			break
+			;;
+
+		*)
+			echo "E: $(basename ${0}): internal error ${0}" >&2
+			exit 1
+			;;
+	esac
+done
+
 if [ ! -x "$(which lxc-info 2>/dev/null)" ]
 then
 	echo "E: lxc-info - no such file" >&2
@@ -19,9 +53,9 @@ for _STATUS in RUNNING FROZEN STOPPED
 do
 	echo ${_STATUS}
 
-	for _CONTAINER in $(lxc-ls)
+	for _CONTAINER in $(lxc-ls -P "${_LXC_DIRECTORY}")
 	do
-		if lxc-info -n ${_CONTAINER} 2>&1 | grep -qs "${_STATUS}"
+		if lxc-info -n ${_CONTAINER} -P "${_LXC_DIRECTORY}" 2>&1 | grep -qs "${_STATUS}"
 		then
 			printf "  %-55.50s" "${_CONTAINER}"
 
diff --git a/debian/local/lxc-ls b/debian/local/lxc-ls
--- a/debian/local/lxc-ls
+++ b/debian/local/lxc-ls
@@ -13,7 +13,37 @@ set -e
 
 _LXC_DIRECTORY="${lxc_path}"
 
-if [ ! -e "${_LXC_DIRECTORY}" ]
+_OPTIONS="$(getopt -o P: -l lxcpath: -- "${@}")"
+
+if [ "${?}" -ne 0 ]
+then
+	echo "Usage: $(basename ${0}) [-P|--lxcpath DIRECTORY]" >&2
+	exit 1
+fi
+
+eval set -- "${_OPTIONS}"
+
+while true
+do
+	case "${1}" in
+	        -P|--lxcpath)
+			_LXC_DIRECTORY="${2}"
+			shift 2
+			;;
+
+		--)
+			shift
+			break
+			;;
+
+		*)
+			echo "E: $(basename ${0}): internal error ${0}" >&2
+			exit 1
+			;;
+	esac
+done
+
+if [ ! -d "${_LXC_DIRECTORY}" ]
 then
 	echo "E: ${_LXC_DIRECTORY}: no such directory." >&2
 	exit 1
