Rediffing lxc-netstat modifications in bash.patch.

diff --git a/debian/patches/03-bash.patch b/debian/patches/03-bash.patch
--- a/debian/patches/03-bash.patch
+++ b/debian/patches/03-bash.patch
@@ -36,8 +36,8 @@ diff -Naurp lxc.orig/src/lxc/lxc-destroy.in lxc/src/lxc/lxc-destroy.in
             btrfs subvolume list "$rootdev" >/dev/null 2>&1; then
              btrfs subvolume delete "$rootdev"
 diff -Naurp lxc.orig/src/lxc/lxc-netstat.in lxc/src/lxc/lxc-netstat.in
---- lxc.orig/src/lxc/lxc-netstat.in	2012-11-12 13:28:25.720114813 +0100
-+++ lxc/src/lxc/lxc-netstat.in	2012-11-12 13:59:03.261226608 +0100
+--- lxc.orig/src/lxc/lxc-netstat.in	2012-12-23 08:54:49.560160061 +0100
++++ lxc/src/lxc/lxc-netstat.in	2012-12-23 08:59:22.276225392 +0100
 @@ -1,4 +1,4 @@
 -#!/bin/bash
 +#!/bin/sh
@@ -46,21 +46,21 @@ diff -Naurp lxc.orig/src/lxc/lxc-netstat.in lxc/src/lxc/lxc-netstat.in
  # lxc: linux Container library
 @@ -58,7 +58,7 @@ get_parent_cgroup()
  
- 		# Return the absolute path to the containers' parent cgroup
- 		# (do not append '/lxc' if the hierarchy contains the 'ns' subsystem)
--		if [[ ",$subsystems," == *,ns,* ]]; then
-+		if [ ",$subsystems," = *,ns,* ]; then
- 			parent_cgroup="${mountpoint}${init_cgroup%/}"
- 		else
- 			parent_cgroup="${mountpoint}${init_cgroup%/}/lxc"
+         # Return the absolute path to the containers' parent cgroup
+         # (do not append '/lxc' if the hierarchy contains the 'ns' subsystem)
+-        if [[ ",$subsystems," == *,ns,* ]]; then
++        if [[ ",$subsystems," = *,ns,* ]]; then
+             parent_cgroup="${mountpoint}${init_cgroup%/}"
+         else
+             parent_cgroup="${mountpoint}${init_cgroup%/}/lxc"
 @@ -119,7 +119,7 @@ fi
  
  tmpdir=$(mktemp -d)
  
 -if [ -z "$tmpdir" -o ! -d "$tmpdir" ]; then
 +if [ -z "$tmpdir" ] || [ ! -d "$tmpdir" ]; then
- 	echo "$(basename $0): unable to create temporary directory" >&2
- 	exit 1
+     echo "$(basename $0): unable to create temporary directory" >&2
+     exit 1
  fi
 diff -Naurp lxc.orig/src/lxc/lxc-ps.in lxc/src/lxc/lxc-ps.in
 --- lxc.orig/src/lxc/lxc-ps.in	2012-11-12 13:28:25.720114813 +0100
