Creating lxc directories in a dangling symlink proof way in order to respect sysadmins decisions for temporary incomplete deployments.

diff --git a/debian/lxc.postinst b/debian/lxc.postinst
--- a/debian/lxc.postinst
+++ b/debian/lxc.postinst
@@ -49,15 +49,17 @@ EOF
 
 		mv -f "${_CONFFILE}.tmp" "${_CONFFILE}"
 
-		# Create lxc directory
-		mkdir -p "${LXC_DIRECTORY}"
-		mkdir -p /etc/lxc/auto
-		mkdir -p /etc/lxc/debconf
+		# Create lxc directories
+		for _DIRECTORY in "${LXC_DIRECTORY}" /etc/lxc/auto /etc/lxc/debconf /usr/share/lxc/cache /usr/share/lxc/packages /var/log/lxc
+		do
+			# Using ls to not fail on (temporarily) dangling symlinks
+			# which might be the sysadmins intention
+			if ! ls "${_DIRECTORY}" > /dev/null 2>&1
+			then
+				mkdir -p "${_DIRECTORY}"
+			fi
+		done
 
-		mkdir -p /usr/share/lxc/cache
-		mkdir -p /usr/share/lxc/packages
-
-		mkdir -p /var/log/lxc
 		chmod 0700 /var/log/lxc
 
 		if [ "${LXC_DIRECTORY}" != "/var/lib/lxc" ]
