Merging upstream version 0.8.0.

diff --git a/templates/lxc-ubuntu-cloud.in b/templates/lxc-ubuntu-cloud.in
--- a/templates/lxc-ubuntu-cloud.in
+++ b/templates/lxc-ubuntu-cloud.in
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-# template script for generating ubuntu container for LXC based on daily cloud
+# template script for generating ubuntu container for LXC based on released cloud
 # images
 #
 # Copyright © 2012 Serge Hallyn <serge.hallyn@canonical.com>
@@ -31,6 +31,7 @@ copy_configuration()
     rootfs=$2
     name=$3
     arch=$4
+    release=$5
 
     if [ $arch = "i386" ]; then
         arch="i686"
@@ -41,7 +42,7 @@ copy_configuration()
     nics=`grep -e '^lxc\.network\.type[ \t]*=[ \t]*veth' $path/config | wc -l`
     if [ $nics -eq 1 ]; then
         grep -q "^lxc.network.hwaddr" $path/config || cat <<EOF >> $path/config
-lxc.network.hwaddr= 00:16:3e:$(openssl rand -hex 3| sed 's/\(..\)/\1:/g; s/.$//')
+lxc.network.hwaddr = 00:16:3e:$(openssl rand -hex 3| sed 's/\(..\)/\1:/g; s/.$//')
 EOF
     fi
 
@@ -54,6 +55,10 @@ lxc.rootfs = $rootfs
 lxc.mount  = $path/fstab
 lxc.arch = $arch
 lxc.cap.drop = sys_module mac_admin
+lxc.pivotdir = lxc_putold
+
+# When using LXC with apparmor, uncomment the next line to run unconfined:
+#lxc.aa_profile = unconfined
 
 lxc.cgroup.devices.deny = a
 # Allow any mknod (but not using the node)
@@ -87,9 +92,18 @@ lxc.cgroup.devices.allow = c 10:232 rwm
 EOF
 
     cat <<EOF > $path/fstab
-proc            $rootfs/proc         proc    nodev,noexec,nosuid 0 0
-sysfs           $rootfs/sys          sysfs defaults  0 0
+proc            proc         proc    nodev,noexec,nosuid 0 0
+sysfs           sys          sysfs defaults  0 0
 EOF
+
+    # rmdir /dev/shm for containers that have /run/shm
+    # I'm afraid of doing rm -rf $rootfs/dev/shm, in case it did
+    # get bind mounted to the host's /run/shm.  So try to rmdir
+    # it, and in case that fails move it out of the way.
+    if [ ! -L $rootfs/dev/shm ] && [ -d $rootfs/run/shm ] && [ -e $rootfs/dev/shm ]; then
+        mv $rootfs/dev/shm $rootfs/dev/shm.bak
+        ln -s /run/shm $rootfs/dev/shm
+    fi
 
     return 0
 }
@@ -104,18 +118,20 @@ Generic Options
 [ -a | --arch ]: Arhcitecture of container, defaults to host arcitecture
 [ -C | --cloud ]: Configure container for use with meta-data service, defaults to no
 [ -T | --tarball ]: Location of tarball
+[ -d | --debug ]: Run with 'set -x' to debug errors
+[ -s | --stream]: Use specified stream rather than 'released'
 
 Options, mutually exclusive of "-C" and "--cloud":
   [ -i | --hostid ]:    HostID for cloud-init, defaults to random string
   [ -u | --userdata ]:  Cloud-init user-data file to configure container on start
-  [ -S | --auth_key ]:  SSH Public key file to inject into container
+  [ -S | --auth-key ]:  SSH Public key file to inject into container
   [ -L | --nolocales ]: Do not copy host's locales into container
 
 EOF
     return 0
 }
 
-options=$(getopt -o a:hp:r:n:Fi:CLS:T: -l arch:,help,path:,release:,name:,flush-cache,hostid:,auth-key:,cloud,no_locales,tarball: -- "$@")
+options=$(getopt -o a:hp:r:n:Fi:CLS:T:ds: -l arch:,help,path:,release:,name:,flush-cache,hostid:,auth-key:,cloud,no_locales,tarball:,debug,stream:,userdata: -- "$@")
 if [ $? -ne 0 ]; then
     usage $(basename $0)
     exit 1
@@ -126,7 +142,7 @@ release=lucid
 if [ -f /etc/lsb-release ]; then
     . /etc/lsb-release
     case "$DISTRIB_CODENAME" in
-        lucid|maverick|natty|oneiric|precise)
+        lucid|natty|oneiric|precise|quantal)
             release=$DISTRIB_CODENAME
         ;;
     esac
@@ -146,14 +162,20 @@ else
     elif [ "$arch" = "x86_64" ]; then
         arch="amd64"
     elif [ "$arch" = "armv7l" ]; then
+        # note: arm images don't exist before oneiric;  are called armhf in
+        # precise and later;  and are not supported by the query, so we don't actually
+        # support them yet (see check later on).  When Query2 is available,
+        # we'll use that to enable arm images.
         arch="armel"
     fi
 fi
 
+debug=0
 hostarch=$arch
 cloud=0
 locales=1
 flushcache=0
+stream="released"
 while true
 do
     case "$1" in
@@ -166,13 +188,19 @@ do
     -i|--hostid)       host_id=$2; shift 2;;
     -u|--userdata)     userdata=$2; shift 2;;
     -C|--cloud)        cloud=1; shift 1;;
-    -S|--auth_key)     auth_key=$2; shift 2;;
+    -S|--auth-key)     auth_key=$2; shift 2;;
     -L|--no_locales)   locales=0; shift 2;;
     -T|--tarball)      tarball=$2; shift 2;;
+    -d|--debug)        debug=1; shift 1;;
+    -s|--stream)       stream=$2; shift 2;;
     --)                shift 1; break ;;
         *)              break ;;
     esac
 done
+
+if [ $debug -eq 1 ]; then
+    set -x
+fi
 
 if [ "$arch" == "i686" ]; then
     arch=i386
@@ -186,6 +214,29 @@ fi
 if [ $arch != "i386" -a $arch != "amd64" ]; then
     echo "Only i386 and amd64 are supported by the ubuntu cloud template."
     exit 1
+fi
+
+if [ "$stream" != "daily" -a "$stream" != "released" ]; then
+    echo "Only 'daily' and 'released' streams are supported"
+    exit 1
+fi
+
+if [ -n "$userdata" ]; then
+    if [ ! -f "$userdata" ]; then
+        echo "Userdata ($userdata) does not exist"
+        exit 1
+    else
+        userdata=`readlink -f $userdata`
+    fi
+fi
+
+if [ -n "$auth_key" ]; then
+    if [ ! -f "$auth_key" ]; then
+        echo "--auth-key=${auth_key} must reference a file"
+        exit 1
+    fi
+    auth_key=$(readlink -f "${auth_key}") ||
+        { echo "failed to get full path for auth_key"; exit 1; }
 fi
 
 if [ -z "$path" ]; then
@@ -210,17 +261,60 @@ cache="/var/cache/lxc/cloud-$release"
 mkdir -p $cache
 
 if [ -n "$tarball" ]; then
-	url2="$tarball"
+    url2="$tarball"
 else
-	url1=`ubuntu-cloudimg-query precise daily $arch --format "%{url}\n"`
-	url2=`echo $url1 | sed -e 's/.tar.gz/-root\0/'`
+    url1=`ubuntu-cloudimg-query $release $stream $arch --format "%{url}\n"`
+    url2=`echo $url1 | sed -e 's/.tar.gz/-root\0/'`
 fi
 
 filename=`basename $url2`
 
+wgetcleanup()
+{
+    rm -f $filename
+}
+
+buildcleanup()
+{
+    cd $rootfs
+    umount -l $cache/$xdir || true
+    rm -rf $cache
+}
+
+# if the release doesn't have a *-rootfs.tar.gz, then create one from the
+# cloudimg.tar.gz by extracting the .img, mounting it loopback, and creating
+# a tarball from the mounted image.
+build_root_tgz()
+{
+    url=$1
+    filename=$2
+
+    xdir=`mktemp -d -p .`
+    tarname=`basename $url`
+    imgname="$release-*-cloudimg-$arch.img"
+    trap buildcleanup EXIT SIGHUP SIGINT SIGTERM
+    if [ $flushcache -eq 1 -o ! -f $cache/$tarname ]; then
+        rm -f $tarname
+        echo "Downloading cloud image from $url"
+        wget $url || { echo "Couldn't find cloud image $url."; exit 1; }
+    fi
+    echo "Creating new cached cloud image rootfs"
+    tar --wildcards -zxf $tarname $imgname
+    mount -o loop $imgname $xdir
+    (cd $xdir; tar zcf ../$filename .)
+    umount $xdir
+    rm -f $tarname $imgname
+    rmdir $xdir
+    echo "New cloud image cache created"
+    trap EXIT
+    trap SIGHUP
+    trap SIGINT
+    trap SIGTERM
+}
+
 mkdir -p /var/lock/subsys/
 (
-    flock -n -x 200
+    flock -x 200
 
     cd $cache
     if [ $flushcache -eq 1 ]; then
@@ -228,77 +322,78 @@ mkdir -p /var/lock/subsys/
         rm -f $filename
     fi
 
+    trap wgetcleanup EXIT SIGHUP SIGINT SIGTERM
     if [ ! -f $filename ]; then
-       wget $url2
+        wget $url2 || build_root_tgz $url1 $filename
     fi
+    trap EXIT
+    trap SIGHUP
+    trap SIGINT
+    trap SIGTERM
 
-    echo "Extracting rootfs"
+    echo "Extracting container rootfs"
     mkdir -p $rootfs
     cd $rootfs
     tar -zxf $cache/$filename
 
 
     if [ $cloud -eq 0 ]; then
-	echo "Configuring for running outside of a cloud environment"
-	echo "If you want to configure for a cloud evironment, please use '-- -C' to create the container"
+        echo "Configuring for running outside of a cloud environment"
+        echo "If you want to configure for a cloud evironment, please use '-- -C' to create the container"
 
-	seed_d=$rootfs/var/lib/cloud/seed/nocloud-net
-	rhostid=$(uuidgen | cut -c -8)
-	host_id=${hostid:-$rhostid}
-	mkdir -p $seed_d
+        seed_d=$rootfs/var/lib/cloud/seed/nocloud-net
+        rhostid=$(uuidgen | cut -c -8)
+        host_id=${hostid:-$rhostid}
+        mkdir -p $seed_d
 
-	cat > "$seed_d/meta-data" <<EOF
-instance_id: lxc-$host_id
+        cat > "$seed_d/meta-data" <<EOF
+instance-id: lxc-$host_id
 EOF
+        if [ -n "$auth_key" ]; then
+            {
+            echo "public-keys:" &&
+            sed -e '/^$/d' -e 's,^,- ,' "$auth_key" "$auth_key"
+            } >> "$seed_d/meta-data"
+            [ $? -eq 0 ] ||
+                { echo "failed to write public keys to metadata"; exit 1; }
+        fi
 
-	rm $rootfs/etc/hostname
+        rm $rootfs/etc/hostname
 
-	if [ $locales -eq 1 ]; then
-		cp /usr/lib/locale/locale-archive $rootfs/usr/lib/locale/locale-archive
-	fi
+        if [ $locales -eq 1 ]; then
+            cp /usr/lib/locale/locale-archive $rootfs/usr/lib/locale/locale-archive
+        fi
 
+        if [ -f "$userdata" ]; then
+            echo "Using custom user-data"
+            cp $userdata $seed_d/user-data
+        else
 
-	if [ -n "$auth_key" -a -f "$auth_key" ]; then
-		u_path="/home/ubuntu/.ssh"
-		root_u_path="$rootfs/$u_path"
-		mkdir -p $root_u_path
-		cp $auth_key "$root_u_path/authorized_keys"
-		chroot $rootfs chown -R ubuntu: "$u_path"
+            if [ -z "$MIRROR" ]; then
+                MIRROR="http://archive.ubuntu.com/ubuntu"
+            fi
 
-		echo "Inserted SSH public key from $auth_key into /home/ubuntu/.ssh/authorized_keys"
-	fi
-
-	if [ ! -f $userdata ]; then
-		cp $userdata $data_d/user-data
-	else
-
-		if [ -z "$MIRROR" ]; then
-			MIRROR="http://archive.ubuntu.com/ubuntu"
-		fi
-
-		cat > "$seed_d/user-data" <<EOF
+            cat > "$seed_d/user-data" <<EOF
 #cloud-config
 output: {all: '| tee -a /var/log/cloud-init-output.log'}
-apt-mirror: $MIRROR
+apt_mirror: $MIRROR
 manage_etc_hosts: localhost
 locale: $(/usr/bin/locale | awk -F= '/LANG=/ {print$NF}')
+password: ubuntu
+chpasswd: { expire: False }
 EOF
+        fi
+    else
 
-	fi
+        echo "Configured for running in a cloud environment."
+        echo "If you do not have a meta-data service, this container will likely be useless."
 
-	chroot $rootfs /usr/sbin/usermod -U ubuntu
-	echo "Please login as user ubuntu with password ubuntu."
-
-   else
-
-	echo "Configured for running in a cloud environment."
-	echo "If you do not have a meta-data service, this container will likely be useless."
-
-   fi
-
+    fi
 ) 200>/var/lock/subsys/lxc-ubucloud
 
-copy_configuration $path $rootfs $name $arch
+copy_configuration $path $rootfs $name $arch $release
 
 echo "Container $name created."
 exit 0
+
+# vi: ts=4 expandtab
