Adding upstream version 1.0.0.

diff --git a/templates/lxc-alpine.in b/templates/lxc-alpine.in
--- a/templates/lxc-alpine.in
+++ b/templates/lxc-alpine.in
@@ -1,7 +1,25 @@
 #!/bin/sh
 
+# Detect use under userns (unsupported)
+for arg in "$@"; do
+    [ "$arg" = "--" ] && break
+    if [ "$arg" = "--mapped-uid" -o "$arg" = "--mapped-gid" ]; then
+        echo "This template can't be used for unprivileged containers." 1>&2
+        echo "You may want to try the \"download\" template instead." 1>&2
+        exit 1
+    fi
+done
+
+# Make sure the usual locations are in PATH
+PATH=$PATH:/usr/sbin:/usr/bin:/sbin:/bin
+export PATH
+
 key_sha256sums="9c102bcc376af1498d549b77bdbfa815ae86faa1d2d82f040e616b18ef2df2d4  alpine-devel@lists.alpinelinux.org-4a6a0840.rsa.pub
-2adcf7ce224f476330b5360ca5edb92fd0bf91c92d83292ed028d7c4e26333ab  alpine-devel@lists.alpinelinux.org-4d07755e.rsa.pub"
+2adcf7ce224f476330b5360ca5edb92fd0bf91c92d83292ed028d7c4e26333ab  alpine-devel@lists.alpinelinux.org-4d07755e.rsa.pub
+ebf31683b56410ecc4c00acd9f6e2839e237a3b62b5ae7ef686705c7ba0396a9  alpine-devel@lists.alpinelinux.org-5243ef4b.rsa.pub
+1bb2a846c0ea4ca9d0e7862f970863857fc33c32f5506098c636a62a726a847b  alpine-devel@lists.alpinelinux.org-524d27bb.rsa.pub
+12f899e55a7691225603d6fb3324940fc51cd7f133e7ead788663c2b7eecb00c  alpine-devel@lists.alpinelinux.org-5261cecb.rsa.pub"
+
 
 get_static_apk () {
     wget="wget -q -O -"
@@ -66,7 +84,8 @@ get_static_apk () {
     if [ "$auto_repo_dir" ]; then
         mirror_list=$rootfs/usr/share/alpine-mirrors/MIRRORS.txt
         mirror_count=$(wc -l $mirror_list | cut -d " " -f 1)
-        repository=$(sed $(expr $RANDOM % $mirror_count + 1)\!d \
+        random=$(hexdump -n 2 -e '/2 "%u"' /dev/urandom)
+        repository=$(sed $(expr $random % $mirror_count + 1)\!d \
             $mirror_list)$auto_repo_dir
         echo "Selecting mirror $repository"
     fi
@@ -109,6 +128,11 @@ tty4:12345:respawn:/sbin/getty 38400 tty4
 ::ctrlaltdel:/sbin/reboot
 ::shutdown:/sbin/rc shutdown
 EOF
+    # set up timezone
+    if [ -f /etc/TZ ]; then
+        cp /etc/TZ "$rootfs/etc/TZ"
+    fi
+
     # set up nameserver
     grep nameserver /etc/resolv.conf > "$rootfs/etc/resolv.conf"
 
@@ -184,7 +208,7 @@ EOF
     if [ "$nics" -eq 1 ] && ! grep -q "^lxc.network.hwaddr" $path/config; then
         # see http://sourceforge.net/tracker/?func=detail&aid=3411497&group_id=163076&atid=826303
         hwaddr="fe:$(dd if=/dev/urandom bs=8 count=1 2>/dev/null |od -t x8 | \
-                      head -1 |awk '{print $2}' | cut -c1-10 |\
+                      head -n 1 |awk '{print $2}' | cut -c1-10 |\
                       sed 's/\(..\)/\1:/g; s/.$//')"
         echo "lxc.network.hwaddr = $hwaddr" >> $path/config
     fi
@@ -194,7 +218,7 @@ EOF
 lxc.tty = 4
 lxc.pts = 1024
 lxc.utsname = $hostname
-lxc.cap.drop = sys_module mac_admin mac_override sys_time
+lxc.cap.drop = sys_module mac_admin mac_override sys_time sys_admin
 
 # When using LXC with apparmor, uncomment the next line to run unconfined:
 #lxc.aa_profile = unconfined
@@ -222,6 +246,7 @@ lxc.cgroup.devices.allow = c 254:0 rm
 lxc.mount.entry=proc proc proc nodev,noexec,nosuid 0 0
 lxc.mount.entry=run run tmpfs nodev,noexec,nosuid,relatime,size=1m,mode=0755 0 0
 lxc.mount.entry=none dev/pts devpts gid=5,mode=620 0 0
+lxc.mount.entry=shm dev/shm tmpfs nodev,nosuid,noexec 0 0
 
 EOF
 
@@ -342,6 +367,9 @@ case "$arch" in
         lxc_arch=i686
         ;;
     x86_64|"")
+        ;;
+    arm*)
+        apk_arch=armhf
         ;;
     *)
         die "unsupported architecture: $arch"
diff --git a/templates/lxc-plamo.in b/templates/lxc-plamo.in
--- a/templates/lxc-plamo.in
+++ b/templates/lxc-plamo.in
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/bin/bash -eu
 
 #
 # template script for generating Plamo Linux container for LXC
@@ -28,50 +28,29 @@
 # ref. https://github.com/Ponce/lxc-slackware/blob/master/lxc-slackware
 #      lxc-ubuntu script
 
+# Detect use under userns (unsupported)
+for arg in "$@"; do
+    [ "$arg" = "--" ] && break
+    if [ "$arg" = "--mapped-uid" -o "$arg" = "--mapped-gid" ]; then
+        echo "This template can't be used for unprivileged containers." 1>&2
+        echo "You may want to try the \"download\" template instead." 1>&2
+        exit 1
+    fi
+done
+
+# Make sure the usual locations are in PATH
+export PATH=$PATH:/usr/sbin:/usr/bin:/sbin:/bin
+
 [ -r /etc/default/lxc ] && . /etc/default/lxc
 
-MIRRORSRV=${MIRRORSRV:-"ftp.ne.jp"}
-MIRRORPATH=${MIRRORPATH:-"/Linux/distributions/plamolinux"}
-CATEGORY[0]=${CATEGORY:-"00_base"}
-PACKAGES[0]=${PACKAGES:-"aaa_base acl at attr bash btrfs_progs bzip2
-    coreutils cracklib dcron devs dhcp dialog dosfstools dump e2fsprogs
-    ed eject etc extipl file findutils gawk glibc grep groff grub gzip
-    hdsetup hibernate_script iproute2 iputils kbd kmod less libcap
-    libgcc libtirpc lilo linux_pam logrotate lvm2 man
-    mdadm microcode_ctl mlocate ncurses net_tools netkit_combo
-    network_configs nvi openbsd_inetd openssh openssl os_prober pciutils
-    pm_utils procinfo_ng procps_ng readline reiserfsprogs rsyslog sed
-    shadow sudo sysfsutils syslinux sysvinit tar tcp_wrappers tcsh
-    timezone traceroute udev unicon_tools util_linux xz zlib"}
-CATEGORY[1]="01_minimum"
-PACKAGES[1]="FDclone autofs bc berkeley_db bsd_games cpio cpufreqd
-    cpufrequtils fortune_mod gc gdbm gpm hddtemp hdparm keyutils libelf
-    libieee1284 libusb libusb_compat libxml2 libzip linux_howto lm_sensors
-    lshw lsof lv man_pages man_pages_ja nilfs_utils nkf pcre perl popt
-    psmisc python recode rpm2targz ruby screen sg3_utils sharutils sqlite
-    squashfs_lzma sysstat texinfo time tree unzip usbutils utempter which
-    yaml zip zsh"
-CATEGORY[2]="01_minimum/alsa.txz"
-PACKAGES[2]="alsa_lib alsa_plugins alsa_utils"
-CATEGORY[3]="01_minimum/aspell.txz"
-PACKAGES[3]="aspell aspell6_en"
-CATEGORY[4]="01_minimum/devel.txz"
-PACKAGES[4]="autoconf automake binutils bison cloog cvs diffutils flex
-    g++ gcc gdb gettext gmp indent intltool kernel_headers libc libtool
-    m4 make mpc mpfr onig patch pkg_config ppl pth slang strace yasm"
-CATEGORY[5]="01_minimum/gnupg_tls.txz"
-PACKAGES[5]="gnupg gnutls gpgme libassuan libgcrypt libgpg_error libksba
-    libtasn1"
-CATEGORY[6]="01_minimum/network.txz"
-PACKAGES[6]="bind bridge_utils curl cyrus_sasl dnsmasq ethtool fetchmail
-    heimdal hostapd iptables iw libidn libiec61883 libnl3 libpcap
-    libraw1394 libssh2 mailx metamail ncftp ntrack parprouted postfix
-    ppp procmail rsync setserial uml_utilities w3m wget wireless_tools
-    wpa_supplicant"
-CATEGORY[7]="01_minimum/nfs.txz"
-PACKAGES[7]="libevent libnfsidmap nfs_utils rpcbind"
-CATEGORY[8]="01_minimum/tcl.txz"
-PACKAGES[8]="expect itcl tcl tclx"
+DLSCHEME=${DLSCHEME:-"http"}
+MIRRORSRV=${MIRRORSRV:-"www.ring.gr.jp"}
+MIRRORPATH=${MIRRORPATH:-"/pub/linux/Plamo"}
+CATEGORIES=${CATEGORIES-"00_base 01_minimum"}
+EXTRACTGRS=${EXTRACTGRS-""}
+IGNOREPKGS=${IGNOREPKGS-"grub kernel lilo linux_firmware microcode_ctl
+    cpufreqd cpufrequtils gpm"}
+ADDONPKGS=${ADDONPKGS-"`echo contrib/Hamradio/{morse,qrq}`"}
 
 download_plamo() {
   # check the mini plamo was not already downloaded
@@ -81,21 +60,42 @@ download_plamo() {
   fi
   # download a mini plamo into a cache
   echo "Downloading Plamo-$release minimal..."
-  echo "open $MIRRORSRV" > /tmp/getpkg
-  for i in `seq 0 $((${#CATEGORY[@]} - 1))` ; do
-    for p in ${PACKAGES[$i]} ; do
-      cat <<- EOF >> /tmp/getpkg
-	mget $MIRRORPATH/Plamo-$release/$arch/plamo/${CATEGORY[$i]}/$p-*.t?z
-	EOF
-    done
-  done
-  echo "close" >> /tmp/getpkg
   cd $ptcache
-  if ! lftp -f /tmp/getpkg ; then
-    echo "Failed to download the rootfs, aborting."
-    return 1
+  case $DLSCHEME in http) depth=2 ;; ftp) depth=3 ;; esac
+  rej=${IGNOREPKGS%% *} ; [ -n "$rej" ] && rej="$rej-*"
+  if [ `echo $IGNOREPKGS | wc -w` -gt 1 ] ; then
+    for p in ${IGNOREPKGS#* } ; do rej="$rej,$p-*" ; done
   fi
-  rm -f /tmp/getpkg
+  for i in $CATEGORIES ; do
+    wget -nv -e robots=off -r -l $depth -nd -A .tgz,.txz -R "$rej" \
+        -I $MIRRORPATH/Plamo-$release/$arch/plamo/$i \
+        -X $MIRRORPATH/Plamo-$release/$arch/plamo/$i/old \
+        $DLSCHEME://$MIRRORSRV$MIRRORPATH/Plamo-$release/$arch/plamo/$i
+    if [ $? -ne 0 ] ; then
+      echo "Failed to download the rootfs, aborting."
+      return 1
+    fi
+  done
+  for i in $EXTRACTGRS ; do
+    wget -nv -e robots=off -r -l $depth -nd -A .tgz,.txz -R "$rej" \
+        -I $MIRRORPATH/Plamo-$release/$arch/contrib/$i \
+        -X $MIRRORPATH/Plamo-$release/$arch/contrib/$i/old \
+        $DLSCHEME://$MIRRORSRV$MIRRORPATH/Plamo-$release/$arch/contrib/$i
+    if [ $? -ne 0 ] ; then
+      echo "Failed to download the rootfs, aborting."
+      return 1
+    fi
+  done
+  for p in $ADDONPKGS ; do
+    wget -nv -e robots=off -r -l $depth -nd -A "`basename $p`-*" \
+        -I $MIRRORPATH/Plamo-$release/$arch/`dirname $p` \
+        -X $MIRRORPATH/Plamo-$release/$arch/`dirname $p`/old \
+        $DLSCHEME://$MIRRORSRV$MIRRORPATH/Plamo-$release/$arch/`dirname $p`
+    if [ $? -ne 0 ] ; then
+      echo "Failed to download the rootfs, aborting."
+      return 1
+    fi
+  done
   mv $ptcache $dlcache
   echo "Download complete."
   return 0
@@ -112,7 +112,7 @@ copy_plamo() {
 install_plamo() {
   mkdir -p @LOCALSTATEDIR@/lock/subsys
   (
-    if ! flock -n 200 ; then
+    if ! flock -n 9 ; then
       echo "Cache repository is busy."
       return 1
     fi
@@ -133,10 +133,8 @@ install_plamo() {
     echo "Installing packages to $rtcache..."
     if [ ! -d $rtcache ] ; then
       mkdir -p $rtcache
-      for i in `seq 0 $((${#CATEGORY[@]} - 1))` ; do
-        for p in ${PACKAGES[$i]} ; do
-          installpkg -root $rtcache -priority ADD $dlcache/$p-*.t?z
-        done
+      for p in `ls -cr $dlcache/*.t?z` ; do
+        installpkg -root $rtcache -priority ADD $p
       done
     fi
     echo "Copy $rtcache to $rootfs..."
@@ -145,7 +143,7 @@ install_plamo() {
       return 1
     fi
     return 0
-  ) 200> @LOCALSTATEDIR@/lock/subsys/lxc
+  ) 9> @LOCALSTATEDIR@/lock/subsys/lxc-plamo
 }
 
 configure_plamo() {
@@ -178,6 +176,12 @@ configure_plamo() {
 	EOF
   # /etc/inittab
   cat <<- "EOF" | patch $rootfs/etc/inittab
+	32,33c32,33
+	< # What to do when power fails (shutdown to single user).
+	< pf::powerfail:/sbin/shutdown -f +5 "THE POWER IS FAILING"
+	---
+	> # What to do when power fails (shutdown).
+	> pf::powerfail:/sbin/shutdown -h +0 "THE POWER IS FAILING"
 	47a48
 	> 1:1235:respawn:/sbin/agetty 38400 console
 	52,53d52
@@ -203,17 +207,17 @@ configure_plamo() {
   echo "Please change root password!"
   # /etc/rc.d/rc.S
   ed - $rootfs/etc/rc.d/rc.S <<- "EOF"
-	230,261d
-	156,163d
-	26,147d
-	16,22d
+	/^mount -w -n -t proc/;/^# ln -s \/bin\/true/-1d
+	/^mknod \/dev\/unikey/;/^# Clean \/etc\/mtab/-2d
+	/^# copy the rules/;/^# Set the hostname/-1d
+	/^# Check the integrity/;/^# Clean up temporary/-1d
 	w
 	EOF
   # /etc/rc.d/rc.M
   ed - $rootfs/etc/rc.d/rc.M <<- "EOF"
-	259,260d
-	56,79d
-	31,38d
+	/^# Screen blanks/;/^# Initialize ip6tables/-1d
+	/^# Initialize sysctl/;/^echo "Starting services/-1d
+	/^sync/;/^# All done/-1d
 	w
 	EOF
   # /etc/rc.d/rc.inet1.tradnet
@@ -237,32 +241,21 @@ configure_plamo() {
 }
 
 copy_configuration() {
-  if ! cat <<- EOF >> $path/config ; then
+  ret=0
+  cat <<- EOF >> $path/config || let ret++
 	lxc.utsname = $name
-	
-	lxc.tty = 4
-	lxc.pts = 1024
-	lxc.mount.auto = proc sys cgroup
+	lxc.mount = $path/fstab
 	lxc.arch = $arch
-	lxc.cap.drop = sys_module mac_admin mac_override sys_time
-	
-	lxc.cgroup.devices.deny = a
-	# /dev/null and zero
-	lxc.cgroup.devices.allow = c 1:3 rwm
-	lxc.cgroup.devices.allow = c 1:5 rwm
-	# consoles
-	lxc.cgroup.devices.allow = c 5:0 rwm
-	lxc.cgroup.devices.allow = c 5:1 rwm
-	# /dev/{,u}random
-	lxc.cgroup.devices.allow = c 1:8 rwm
-	lxc.cgroup.devices.allow = c 1:9 rwm
-	lxc.cgroup.devices.allow = c 5:2 rwm
-	lxc.cgroup.devices.allow = c 136:* rwm
-	# rtc
-	lxc.cgroup.devices.allow = c 254:0 rm
-	# fuse
-	lxc.cgroup.devices.allow = c 10:229 rwm
 	EOF
+  if [ -f "@LXCTEMPLATECONFIG@/plamo.common.conf" ] ; then
+    cat <<- "EOF" >> $path/config || let ret++
+	
+	lxc.include = @LXCTEMPLATECONFIG@/plamo.common.conf
+	EOF
+  fi
+  # create the fstab (empty by default)
+  touch $path/fstab || let ret++
+  if [ $ret -ne 0 ] ; then
     echo "Failed to add configuration."
     return 1
   fi
@@ -292,7 +285,7 @@ cleanup() {
   [ -d $dlcache -a -d $rtcache ] || return 0
   # lock, so we won't purge while someone is creating a repository
   (
-    if ! flock -n 200 ; then
+    if ! flock -n 9 ; then
       echo "Cache repository is busy."
       return 1
     fi
@@ -300,17 +293,17 @@ cleanup() {
     rm -rf --one-file-system $dlcache $rtcache || return 1
     echo "Done."
     return 0
-  ) 200> @LOCALSTATEDIR@/lock/subsys/lxc
+  ) 9> @LOCALSTATEDIR@/lock/subsys/lxc-plamo
 }
 
 usage() {
   cat <<- EOF
 	$prog [-h|--help] -p|--path=<path> -n|--name=<name> --rootfs=<rootfs>
-	          [--clean] [-r|--release=<release>] [-b|--bindhome=<user>]
-	          [-a|--arch=<arch>]
+	          [--clean] [-r|--release=<release>] [-a|--arch=<arch>]
+	          [-b|--bindhome=<user>]
 	release: $release
-	bindhome: bind <user>'s home into the container
 	arch: x86 or x86_64: defaults to host arch
+	bindhome: bind <user>'s home into the container
 	EOF
 }
 
@@ -318,10 +311,10 @@ prog=`basename $0`
 path="" ; name="" ; rootfs=""
 clean=0
 release=${release:-5.x}
-bindhome=""
 arch=`uname -m | sed 's/i.86/x86/'` ; hostarch=$arch
-sopts=hp:n:cr:b:a:
-lopts=help,path:,name:,rootfs:,clean,release:,bindhome:,arch:
+bindhome=""
+sopts=hp:n:cr:a:b:
+lopts=help,path:,name:,rootfs:,clean,release:,arch:,bindhome:
 if ! options=`getopt -o $sopts -l $lopts -- "$@"` ; then
   usage
   exit 1
@@ -335,8 +328,8 @@ while true ; do
   --rootfs) rootfs=$2 ; shift 2 ;;
   -c|--clean) clean=1 ; shift 1 ;;
   -r|--release) release=$2 ; shift 2 ;;
-  -b|--bindhome) bindhome=$2 ; shift 2 ;;
   -a|--arch) arch=$2 ; shift 2 ;;
+  -b|--bindhome) bindhome=$2 ; shift 2 ;;
   --) shift 1 ; break ;;
   *) break ;;
   esac
@@ -367,7 +360,7 @@ dlcache=$cache/cache-${prog##*-}-$release-$arch
 rtcache=$cache/rootfs-${prog##*-}-$release-$arch
 if [ -z "$rootfs" ] ; then
   if grep -q "^lxc.rootfs" $path/config ; then
-    rootfs=$(awk -F= '/^lxc.rootfs =/{ print $2 }' $path/config)
+    rootfs=`awk -F= '/^lxc.rootfs =/{ print $2 }' $path/config`
   else
     rootfs=$path/rootfs
   fi
diff --git a/templates/lxc-ubuntu.in b/templates/lxc-ubuntu.in
--- a/templates/lxc-ubuntu.in
+++ b/templates/lxc-ubuntu.in
@@ -24,6 +24,19 @@
 #  License along with this library; if not, write to the Free Software
 #  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 
+# Detect use under userns (unsupported)
+for arg in "$@"; do
+    [ "$arg" = "--" ] && break
+    if [ "$arg" = "--mapped-uid" -o "$arg" = "--mapped-gid" ]; then
+        echo "This template can't be used for unprivileged containers." 1>&2
+        echo "You may want to try the \"download\" template instead." 1>&2
+        exit 1
+    fi
+done
+
+# Make sure the usual locations are in PATH
+export PATH=$PATH:/usr/sbin:/usr/bin:/sbin:/bin
+
 set -e
 
 LOCALSTATEDIR="@LOCALSTATEDIR@"
@@ -87,15 +100,15 @@ EOF
 
     # make sure we have the current locale defined in the container
     if [ -z "$LANG" ] || echo $LANG | grep -E -q "^C(\..+)*$"; then
-        chroot $rootfs locale-gen en_US.UTF-8
-        chroot $rootfs update-locale LANG=en_US.UTF-8
+        chroot $rootfs locale-gen en_US.UTF-8 || true
+        chroot $rootfs update-locale LANG=en_US.UTF-8 || true
     else
-        chroot $rootfs locale-gen $LANG
-        chroot $rootfs update-locale LANG=$LANG
+        chroot $rootfs locale-gen $LANG || true
+        chroot $rootfs update-locale LANG=$LANG || true
     fi
 
     # generate new SSH keys
-    if [ -x $rootfs$LOCALSTATEDIR/lib/dpkg/info/openssh-server.postinst ]; then
+    if [ -x $rootfs/var/lib/dpkg/info/openssh-server.postinst ]; then
         cat > $rootfs/usr/sbin/policy-rc.d << EOF
 #!/bin/sh
 exit 101
@@ -104,7 +117,7 @@ EOF
 
         rm -f $rootfs/etc/ssh/ssh_host_*key*
         mv $rootfs/etc/init/ssh.conf $rootfs/etc/init/ssh.conf.disabled
-        DPKG_MAINTSCRIPT_PACKAGE=openssh DPKG_MAINTSCRIPT_NAME=postinst chroot $rootfs $LOCALSTATEDIR/lib/dpkg/info/openssh-server.postinst configure
+        DPKG_MAINTSCRIPT_PACKAGE=openssh DPKG_MAINTSCRIPT_NAME=postinst chroot $rootfs /var/lib/dpkg/info/openssh-server.postinst configure
         mv $rootfs/etc/init/ssh.conf.disabled $rootfs/etc/init/ssh.conf
 
         sed -i "s/root@$(hostname)/root@$hostname/g" $rootfs/etc/ssh/ssh_host_*.pub
@@ -147,6 +160,33 @@ finalize_user()
     return 0
 }
 
+# A function to try and autodetect squid-deb-proxy servers on the local network
+# if either the squid-deb-proxy-client package is installed on the host or
+# a parent container set the 50squid-deb-proxy-client file.
+squid_deb_proxy_autodetect()
+{
+    local apt_discover=/usr/share/squid-deb-proxy-client/apt-avahi-discover
+    local proxy_file=/etc/apt/apt.conf.d/50squid-deb-proxy-client
+    squid_proxy_line=  # That's a global :/
+
+    # Maybe the host is aware of a squid-deb-proxy?
+    if [ -f $apt_discover ]; then
+        echo -n "Discovering squid-deb-proxy..."
+        squid_proxy_line=$($apt_discover)
+        if [ -n "$squid_proxy_line" ]; then
+            echo "found squid-deb-proxy: $squid_proxy_line"
+        else
+            echo "no squid-deb-proxy found"
+        fi
+    fi
+
+    # Are we in a nested container, and the parent already knows of a proxy?
+    if [ -f $proxy_file ]; then
+        # Extract the squid URL from the file (whatever is between "")
+        squid_proxy_line=`cat $proxy_file | sed "s/.*\"\(.*\)\".*/\1/"`
+    fi
+}
+
 #
 # Choose proxies for container
 # http_proxy will be used by debootstrap on the host.
@@ -162,7 +202,13 @@ choose_container_proxy()
     fi
     case "$HTTP_PROXY" in
     none)
-        APT_PROXY=
+        squid_deb_proxy_autodetect
+        if [ -n "$squid_proxy_line" ]; then
+            APT_PROXY=$squid_proxy_line
+            export http_proxy=$squid_proxy_line
+        else
+            APT_PROXY=
+        fi
         ;;
     apt)
         RES=`apt-config shell APT_PROXY Acquire::http::Proxy`
@@ -239,7 +285,7 @@ cleanup()
 suggest_flush()
 {
     echo "Container upgrade failed.  The container cache may be out of date,"
-    echo "in which case flushing the case (see -F in the hep output) may help."
+    echo "in which case flushing the cache (see -F in the help output) may help."
 }
 
 download_ubuntu()
@@ -338,7 +384,7 @@ install_ubuntu()
     mkdir -p $LOCALSTATEDIR/lock/subsys/
 
     (
-        flock -x 200
+        flock -x 9
         if [ $? -ne 0 ]; then
             echo "Cache repository is busy."
             return 1
@@ -369,7 +415,7 @@ install_ubuntu()
 
         return 0
 
-    ) 200>$LOCALSTATEDIR/lock/subsys/lxc-ubuntu$release
+    ) 9>$LOCALSTATEDIR/lock/subsys/lxc-ubuntu$release
 
     return $?
 }
@@ -519,7 +565,7 @@ EOF
         cat /etc/timezone > $rootfs/etc/timezone
         chroot $rootfs dpkg-reconfigure -f noninteractive tzdata
     elif [ -f /etc/sysconfig/clock ]; then
-        source /etc/sysconfig/clock
+        . /etc/sysconfig/clock
         echo $ZONE > $rootfs/etc/timezone
         chroot $rootfs dpkg-reconfigure -f noninteractive tzdata
     else
@@ -625,6 +671,10 @@ else
         arch="amd64"
     elif [ "$arch" = "armv7l" ]; then
         arch="armhf"
+    elif [ "$arch" = "aarch64" ]; then
+        arch="arm64"
+    elif [ "$arch" = "ppc64le" ]; then
+        arch="ppc64el"
     fi
 fi
 
@@ -670,7 +720,7 @@ if [ -n "$bindhome" ]; then
 fi
 
 
-if [ "$arch" == "i686" ]; then
+if [ "$arch" = "i686" ]; then
     arch=i386
 fi
 
@@ -679,8 +729,13 @@ if [ $hostarch = "i386" -a $arch = "amd64" ]; then
     exit 1
 fi
 
-if [ $hostarch = "armhf" -o $hostarch = "armel" ] && \
-   [ $arch != "armhf" -a $arch != "armel" ]; then
+if [ $hostarch = "armhf" -o $hostarch = "armel" -o $hostarch = "arm64" ] && \
+   [ $arch != "armhf" -a $arch != "armel" -a $arch != "arm64" ]; then
+    echo "can't create $arch container on $hostarch"
+    exit 1
+fi
+
+if [ $arch = "arm64" ] && [ $hostarch != "arm64" ]; then
     echo "can't create $arch container on $hostarch"
     exit 1
 fi
