Merging upstream version 1.0.0~alpha2.

diff --git a/templates/lxc-debian.in b/templates/lxc-debian.in
--- a/templates/lxc-debian.in
+++ b/templates/lxc-debian.in
@@ -20,7 +20,6 @@
 # License along with this library; if not, write to the Free Software
 # Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
 
-SUITE=${SUITE:-squeeze}
 MIRROR=${MIRROR:-http://cdn.debian.net/debian}
 
 configure_debian()
@@ -81,7 +80,10 @@ EOF
         chroot $rootfs locale-gen en_US.UTF-8 UTF-8
         chroot $rootfs update-locale LANG=en_US.UTF-8
     else
-        chroot $rootfs locale-gen $LANG $(echo $LANG | cut -d. -f2)
+        encoding=$(echo $LANG | cut -d. -f2)
+        chroot $rootfs sed -e "s/^# \(${LANG} ${encoding}\)/\1/" \
+            -i /etc/locale.gen 2>/dev/null
+        chroot $rootfs locale-gen $LANG $encoding
         chroot $rootfs update-locale LANG=$LANG
     fi
 
@@ -99,8 +101,8 @@ EOF
 
 cleanup()
 {
-    rm -rf $cache/partial-$SUITE-$arch
-    rm -rf $cache/rootfs-$SUITE-$arch
+    rm -rf $cache/partial-$release-$arch
+    rm -rf $cache/rootfs-$release-$arch
 }
 
 download_debian()
@@ -118,12 +120,13 @@ openssh-server
 
     cache=$1
     arch=$2
+    release=$3
 
     trap cleanup EXIT SIGHUP SIGINT SIGTERM
     # check the mini debian was not already downloaded
-    mkdir -p "$cache/partial-$SUITE-$arch"
+    mkdir -p "$cache/partial-$release-$arch"
     if [ $? -ne 0 ]; then
-        echo "Failed to create '$cache/partial-$SUITE-$arch' directory"
+        echo "Failed to create '$cache/partial-$release-$arch' directory"
         return 1
     fi
 
@@ -131,13 +134,13 @@ openssh-server
     echo "Downloading debian minimal ..."
     debootstrap --verbose --variant=minbase --arch=$arch \
         --include=$packages \
-        "$SUITE" "$cache/partial-$SUITE-$arch" $MIRROR
+        "$release" "$cache/partial-$release-$arch" $MIRROR
     if [ $? -ne 0 ]; then
         echo "Failed to download the rootfs, aborting."
         return 1
     fi
 
-    mv "$1/partial-$SUITE-$arch" "$1/rootfs-$SUITE-$arch"
+    mv "$1/partial-$release-$arch" "$1/rootfs-$release-$arch"
     echo "Download complete."
     trap EXIT
     trap SIGINT
@@ -152,11 +155,12 @@ copy_debian()
     cache=$1
     arch=$2
     rootfs=$3
+    release=$4
 
     # make a local copy of the minidebian
     echo -n "Copying rootfs to $rootfs..."
     mkdir -p $rootfs
-    rsync -Ha "$cache/rootfs-$SUITE-$arch"/ $rootfs/ || return 1
+    rsync -Ha "$cache/rootfs-$release-$arch"/ $rootfs/ || return 1
     return 0
 }
 
@@ -164,6 +168,8 @@ install_debian()
 {
     cache="@LOCALSTATEDIR@/cache/lxc/debian"
     rootfs=$1
+    release=$2
+    arch=$3
     mkdir -p @LOCALSTATEDIR@/lock/subsys/
     (
         flock -x 200
@@ -172,29 +178,16 @@ install_debian()
             return 1
         fi
 
-        if which dpkg >/dev/null 2>&1 ; then
-            arch=$(dpkg --print-architecture)
-        else
-            arch=$(uname -m)
-            if [ "$arch" = "i686" ]; then
-                arch="i386"
-            elif [ "$arch" = "x86_64" ]; then
-                arch="amd64"
-            elif [ "$arch" = "armv7l" ]; then
-                arch="armhf"
-            fi
-        fi
-
-        echo "Checking cache download in $cache/rootfs-$SUITE-$arch ... "
-        if [ ! -e "$cache/rootfs-$SUITE-$arch" ]; then
-            download_debian $cache $arch
+        echo "Checking cache download in $cache/rootfs-$release-$arch ... "
+        if [ ! -e "$cache/rootfs-$release-$arch" ]; then
+            download_debian $cache $arch $release
             if [ $? -ne 0 ]; then
                 echo "Failed to download 'debian base'"
                 return 1
             fi
         fi
 
-        copy_debian $cache $arch $rootfs
+        copy_debian $cache $arch $rootfs $release
         if [ $? -ne 0 ]; then
             echo "Failed to copy rootfs"
             return 1
@@ -212,11 +205,13 @@ copy_configuration()
     path=$1
     rootfs=$2
     hostname=$3
+    arch=$4
 
     grep -q "^lxc.rootfs" $path/config 2>/dev/null || echo "lxc.rootfs = $rootfs" >> $path/config
     cat <<EOF >> $path/config
 lxc.tty = 4
 lxc.pts = 1024
+lxc.arch = $arch
 lxc.utsname = $hostname
 lxc.cap.drop = sys_module mac_admin mac_override sys_time
 
@@ -279,24 +274,42 @@ clean()
 usage()
 {
     cat <<EOF
-$1 -h|--help -p|--path=<path> --clean
+$1 -h|--help -p|--path=<path> [-a|--arch] [-r|--release=<release>] [-c|--clean]
+release: the debian release (e.g. wheezy): defaults to current stable
+arch: the container architecture (e.g. amd64): defaults to host arch
 EOF
     return 0
 }
 
-options=$(getopt -o hp:n:c -l help,rootfs:,path:,name:,clean -- "$@")
+options=$(getopt -o hp:n:a:r:c -l help,rootfs:,path:,name:,arch:,release:,clean -- "$@")
 if [ $? -ne 0 ]; then
         usage $(basename $0)
         exit 1
 fi
 eval set -- "$options"
 
+if which dpkg >/dev/null 2>&1 ; then
+    arch=$(dpkg --print-architecture)
+else
+    arch=$(uname -m)
+    if [ "$arch" = "i686" ]; then
+        arch="i386"
+    elif [ "$arch" = "x86_64" ]; then
+        arch="amd64"
+    elif [ "$arch" = "armv7l" ]; then
+        arch="armhf"
+    fi
+fi
+hostarch=$arch
+
 while true
 do
     case "$1" in
-        -h|--help)      usage $0 && exit 0;;
+        -h|--help)      usage $0 && exit 1;;
         -p|--path)      path=$2; shift 2;;
         --rootfs)       rootfs=$2; shift 2;;
+        -a|--arch)      arch=$2; shift 2;;
+        -r|--release)   release=$2; shift 2;;
         -n|--name)      name=$2; shift 2;;
         -c|--clean)     clean=$2; shift 2;;
         --)             shift 1; break ;;
@@ -307,6 +320,30 @@ done
 if [ ! -z "$clean" -a -z "$path" ]; then
     clean || exit 1
     exit 0
+fi
+
+if [ "$arch" == "i686" ]; then
+    arch=i386
+fi
+
+if [ "$arch" == "x86_64" ]; then
+    arch=amd64
+fi
+
+if [ $hostarch = "i386" -a $arch = "amd64" ]; then
+    echo "can't create $arch container on $hostarch"
+    exit 1
+fi
+
+if [ $hostarch = "armhf" -o $hostarch = "armel" ] && \
+   [ $arch != "armhf" -a $arch != "armel" ]; then
+    echo "can't create $arch container on $hostarch"
+    exit 1
+fi
+
+if [ $hostarch = "powerpc" -a $arch != "powerpc" ]; then
+    echo "can't create $arch container on $hostarch"
+    exit 1
 fi
 
 type debootstrap
@@ -325,6 +362,16 @@ if [ "$(id -u)" != "0" ]; then
     exit 1
 fi
 
+current_release=`wget ${MIRROR}/dists/stable/Release -O - 2>/dev/null |\
+head |awk '/^Codename: (.*)$/ { print $2; }'`
+release=${release:-${current_release}}
+valid_releases=('squeeze' 'wheezy' 'jessie' 'sid')
+if [[ ! "${valid_releases[*]}" =~ (^|[^[:alpha:]])$release([^[:alpha:]]|$) ]]
+then
+    echo "Invalid release ${release}, valid ones are: ${valid_releases[*]}"
+    exit 1
+fi
+
 # detect rootfs
 config="$path/config"
 if [ -z "$rootfs" ]; then
@@ -336,7 +383,7 @@ if [ -z "$rootfs" ]; then
 fi
 
 
-install_debian $rootfs
+install_debian $rootfs $release $arch
 if [ $? -ne 0 ]; then
     echo "failed to install debian"
     exit 1
@@ -348,7 +395,7 @@ if [ $? -ne 0 ]; then
     exit 1
 fi
 
-copy_configuration $path $rootfs $name
+copy_configuration $path $rootfs $name $arch
 if [ $? -ne 0 ]; then
     echo "failed write configuration file"
     exit 1
